### ISSUE TITLE
MediaType error when running the plugin

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-imageJ-plugin#12]
I got the following error message after trying to run the plugin. I'm using FIJI (the newest version of imageJ). Has it been tested only on Vanilla ImageJ? Or did I mess something up when installing?

![image](https://user-images.githubusercontent.com/13770365/90528547-99e33580-e127-11ea-8161-af723c0d5d78.png)

**Comment by willgraf** [comment]
I have only tested this plugin with ImageJ, and the install instructions in this README are only for ImageJ.

It looks like the following is broken with FIJI:

```
import okhttp3.MediaType;
static final MediaType MEDIA_TYPE_JSON = MediaType.get("application/json; charset=utf-8");
```

But [it is indeed a method](https://square.github.io/okhttp/3.x/okhttp/index.html?okhttp3/MediaType.html).

**Comment by ngreenwald** [comment]
Yup, I downloaded ImageJ and it works there. Looks like ImageJ2/FIJI issue

**Comment by willgraf** [comment]
I've just downloaded and installed the lateset versions of ImageJ 2 and FIJI, and it worked successfully on both (segmentation jobs).

How did you install it in FIJI?

**Comment by ngreenwald** [comment]
I hadn't updated FIJI in like 4 months. Works great. 
![image](https://user-images.githubusercontent.com/13770365/90562718-7df78800-e157-11ea-9a66-d916da2844d5.png)
