### ISSUE TITLE
Add more explanation for QuPath/ImageJ

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-imageJ-plugin#30]
Given the great feedback we got from Z yesterday on how to convert to ROIs, and also how to integrate with QuPath, we should update the ReadMe to give more guidance on how to use the tools once the plugin is installed

**Comment by willgraf** [comment]
I think that the README already contains information on using the plugin with QuPath as well as the link to the groovy script.

I think the remainder of this work can be tracked by #39, so I will close this issue.
