### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-imageJ-plugin#31]
Given that the repo works for both QuPath and FIJI, and that most of the use case is actually not for ImageJ, maybe we should consider changing the name?

**Comment by willgraf** [comment]
I'm open to new names but this project really IS an ImageJ plugin, which is what makes it compatible with QuPath and FIJI.

**Comment by ngreenwald** [comment]
Yeah, agreed
