### ISSUE TITLE
502 response error when submitting large numbers of images

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-imageJ-plugin#33]
Using the new QuPath script that Pete put together is producing a 502 error message (described in the thread below). It's only around 200 images, so I don't think it's a deepcell.org issue, perhaps QuPath is handling them serially which is causing the bottleneck?

https://forum.image.sc/t/deepcell-tiling/46105

**Comment by willgraf** [comment]
The 502 error is definitely an issue on our end - The server was temporarily down (maybe the webserver got spun down mid-request or something).

The plugin should likely retry failed attempts a few times before failing, which should resolve this issue.
